export type {
  Contact,
  CrmPipelineColumn,
  Interaction,
  InteractionType,
  Lead,
  LeadSource,
  LeadStatus,
  Opportunity,
  Organization,
  OrganizationType,
  Project,
  ProjectStatus,
  Proposal,
  ProposalStatus,
} from "@/types/crm";

export {
  CRM_PIPELINE_COLUMNS,
  INTERACTION_TYPES,
  LEAD_SOURCE_LABELS,
  LEAD_SOURCES,
  LEAD_STATUS_LABELS,
  LEAD_STATUSES,
  ORGANIZATION_TYPES,
  PROJECT_STATUSES,
  PROPOSAL_STATUSES,
} from "@/types/crm";

export type {
  AutomationOpportunity,
  CurrentProcess,
  CurrentProcessStep,
  Diagnosis,
  DiagnosisPriority,
  DiagnosisScoreDimensions,
  DiagnosisStatus,
  Impact,
  Observation,
  Problem,
  ProposedProcess,
  ProposedProcessStep,
  Recommendation,
  RootCause,
  Solution,
} from "@/types/diagnosis";

export {
  AUTOMATION_TYPES,
  DIAGNOSIS_FORM_STAGES,
  DIAGNOSIS_METHODOLOGY_STAGES,
  DIAGNOSIS_PRIORITIES,
  DIAGNOSIS_STATUSES,
  DIAGNOSIS_VIEW_TABS,
  EVIDENCE_LEVELS,
  IMPACT_CATEGORIES,
  OBSERVATION_AREAS,
  RECOMMENDATION_HORIZONS,
  ROOT_CAUSE_CATEGORIES,
  SOLUTION_TYPES,
} from "@/types/diagnosis";
