/**
 * Seed mock A&D — separado de la UI y de cualquier API real.
 */
import type {
  AdAccount,
  AdAppSettings,
  AdAuditEvent,
  AdCategory,
  AdCustomer,
  AdDailyClosure,
  AdInventoryClosure,
  AdInventoryItem,
  AdInventoryMovement,
  AdOperator,
  AdPaymentMethodConfig,
  AdPrepaidAccount,
  AdPrepaidConsumption,
  AdPresentation,
  AdProduct,
  AdPurchase,
  AdReceipt,
  AdSale,
  AdServiceLog,
  AdTable,
  AdWarehouse,
  AdWhatsAppLog,
} from "@/types/ad-licoreria";

const now = () => new Date().toISOString();

export const AD_DEMO_SETTINGS: AdAppSettings = {
  exchangeRateUsdToBs: 370,
  suggestBsFromRate: true,
  brandName: "A&D",
  brandTagline: "LICORERÍA & BODEGÓN",
  whatsappEnabled: true,
};

export const AD_DEMO_PAYMENT_METHODS: AdPaymentMethodConfig[] = [
  {
    id: "pm-cash-usd",
    code: "efectivo_usd",
    name: "Efectivo USD",
    currency: "USD",
    active: true,
    requiresReference: false,
    requiresVoucher: false,
    requiresBank: false,
    notes: "Billetes USD",
  },
  {
    id: "pm-cash-bs",
    code: "efectivo_bs",
    name: "Efectivo Bs",
    currency: "BS",
    active: true,
    requiresReference: false,
    requiresVoucher: false,
    requiresBank: false,
  },
  {
    id: "pm-pago-movil",
    code: "pago_movil",
    name: "Pago móvil",
    currency: "BS",
    active: true,
    requiresReference: true,
    requiresVoucher: false,
    requiresBank: true,
    notes: "Banco + referencia + teléfono origen",
  },
  {
    id: "pm-transfer",
    code: "transferencia",
    name: "Transferencia",
    currency: "BS",
    active: true,
    requiresReference: true,
    requiresVoucher: true,
    requiresBank: true,
  },
  {
    id: "pm-zelle",
    code: "zelle",
    name: "Zelle",
    currency: "USD",
    active: true,
    requiresReference: true,
    requiresVoucher: false,
    requiresBank: false,
  },
  {
    id: "pm-card",
    code: "tarjeta",
    name: "Tarjeta",
    currency: "BS",
    active: true,
    requiresReference: true,
    requiresVoucher: false,
    requiresBank: false,
  },
  {
    id: "pm-qr",
    code: "qr",
    name: "QR",
    currency: "USD",
    active: true,
    requiresReference: true,
    requiresVoucher: false,
    requiresBank: false,
  },
  {
    id: "pm-other",
    code: "otro",
    name: "Otro",
    currency: "USD",
    active: true,
    requiresReference: false,
    requiresVoucher: false,
    requiresBank: false,
    notes: "Especificar en observaciones",
  },
];

export const AD_DEMO_OPERATORS: AdOperator[] = [
  {
    id: "op-admin",
    username: "admin",
    name: "Administrador",
    role: "admin",
    active: true,
    warehouseId: null,
    posEnabled: false,
    inventoryAccess: true,
    copAccess: true,
    purchaseAccess: true,
    closuresAccess: true,
    createdAt: now(),
  },
  {
    id: "op-supervisor",
    username: "supervisor",
    name: "Supervisor A&D",
    phone: "0412-0000001",
    role: "supervisor",
    active: true,
    warehouseId: null,
    posEnabled: false,
    inventoryAccess: true,
    copAccess: true,
    purchaseAccess: true,
    closuresAccess: true,
    createdAt: now(),
  },
  {
    id: "op-maria",
    username: "maria",
    name: "María",
    phone: "0414-1111001",
    role: "cajero",
    active: true,
    warehouseId: "wh-2",
    posEnabled: true,
    inventoryAccess: false,
    copAccess: false,
    purchaseAccess: false,
    closuresAccess: true,
    createdAt: now(),
  },
  {
    id: "op-carlos",
    username: "carlos",
    name: "Carlos",
    phone: "0414-2222002",
    role: "cajero",
    active: true,
    warehouseId: "wh-1",
    posEnabled: true,
    inventoryAccess: false,
    copAccess: false,
    purchaseAccess: false,
    closuresAccess: true,
    createdAt: now(),
  },
  {
    id: "op-ana",
    username: "ana",
    name: "Ana",
    phone: "0414-3333003",
    role: "mesonera",
    active: true,
    warehouseId: "wh-2",
    posEnabled: false,
    inventoryAccess: false,
    copAccess: false,
    purchaseAccess: false,
    closuresAccess: false,
    createdAt: now(),
  },
  {
    id: "op-pedro",
    username: "pedro",
    name: "Pedro",
    phone: "0414-4444004",
    role: "inventario",
    active: true,
    warehouseId: null,
    posEnabled: false,
    inventoryAccess: true,
    copAccess: true,
    purchaseAccess: true,
    closuresAccess: false,
    createdAt: now(),
  },
];

export const AD_DEMO_CATEGORIES: AdCategory[] = [
  { id: "cat-cerveza", name: "Cervezas", slug: "cervezas", active: true },
  { id: "cat-licor", name: "Licores", slug: "licores", active: true },
  { id: "cat-whisky", name: "Whisky", slug: "whisky", active: true },
  { id: "cat-ron", name: "Ron", slug: "ron", active: true },
  { id: "cat-vodka", name: "Vodka", slug: "vodka", active: true },
  { id: "cat-ginebra", name: "Ginebra", slug: "ginebra", active: true },
  { id: "cat-tequila", name: "Tequila", slug: "tequila", active: true },
  { id: "cat-vino", name: "Vinos", slug: "vinos", active: true },
  { id: "cat-refresco", name: "Refrescos", slug: "refrescos", active: true },
  { id: "cat-agua", name: "Agua", slug: "agua", active: true },
  { id: "cat-hielo", name: "Hielo", slug: "hielo", active: true },
  { id: "cat-snack", name: "Snacks", slug: "snacks", active: true },
  { id: "cat-comida", name: "Comida", slug: "comida", active: true },
  { id: "cat-otro", name: "Otros", slug: "otros", active: true },
];

export const AD_DEMO_WAREHOUSES: AdWarehouse[] = [
  {
    id: "wh-1",
    name: "Bodegón",
    code: "WH-002",
    kind: "principal",
    active: true,
    responsibleUserId: "op-carlos",
  },
  {
    id: "wh-2",
    name: "Licorería",
    code: "WH-001",
    kind: "barra",
    active: true,
    responsibleUserId: "op-maria",
  },
];

export const AD_DEMO_PRODUCTS: AdProduct[] = [
  {
    id: "prod-regional",
    name: "Cerveza Regional",
    brand: "Regional",
    categoryId: "cat-cerveza",
    sku: "CER-REG",
    barcode: "7591001000100",
    description: "Cerveza Regional",
    baseUnitLabel: "unidad",
    cost: { usd: 0.5, bs: 185 },
    minStockBase: 48,
    active: true,
    createdAt: now(),
  },
  {
    id: "prod-polar",
    name: "Cerveza Polar",
    brand: "Polar",
    categoryId: "cat-cerveza",
    sku: "CER-POLAR",
    baseUnitLabel: "unidad",
    cost: { usd: 0.55, bs: 200 },
    minStockBase: 36,
    active: true,
    createdAt: now(),
  },
  {
    id: "prod-ron",
    name: "Ron Santa Teresa Gran Reserva",
    brand: "Santa Teresa",
    categoryId: "cat-ron",
    sku: "RON-ST-GR",
    baseUnitLabel: "botella",
    cost: { usd: 12, bs: 4440 },
    minStockBase: 6,
    active: true,
    createdAt: now(),
  },
  {
    id: "prod-refresco",
    name: "Refresco 1.5L",
    brand: "Pepsi",
    categoryId: "cat-refresco",
    sku: "REF-15",
    baseUnitLabel: "unidad",
    cost: { usd: 0.9, bs: 330 },
    minStockBase: 12,
    active: true,
    createdAt: now(),
  },
  {
    id: "prod-agua",
    name: "Agua mineral 600ml",
    brand: "Minalba",
    categoryId: "cat-agua",
    sku: "AGU-600",
    baseUnitLabel: "unidad",
    cost: { usd: 0.3, bs: 110 },
    minStockBase: 24,
    active: true,
    createdAt: now(),
  },
];

/** Conversiones configurables (no hardcodeadas en lógica de negocio). */
export const AD_DEMO_PRESENTATIONS: AdPresentation[] = [
  {
    id: "pres-reg-1",
    productId: "prod-regional",
    name: "Individual",
    code: "REG-1",
    unitsPerPresentation: 1,
    price: { usd: 1, bs: 370 },
    minPrice: { usd: 0.8, bs: 296 },
    maxPrice: { usd: 1.5, bs: 555 },
    active: true,
  },
  {
    id: "pres-reg-balde",
    productId: "prod-regional",
    name: "Balde",
    code: "REG-BALDE",
    unitsPerPresentation: 10,
    price: { usd: 5, bs: 1850 },
    minPrice: { usd: 4.5, bs: 1665 },
    maxPrice: { usd: 6, bs: 2220 },
    active: true,
  },
  {
    id: "pres-reg-caja",
    productId: "prod-regional",
    name: "Caja x36",
    code: "REG-CAJA",
    unitsPerPresentation: 36,
    price: { usd: 30, bs: 11100 },
    active: true,
  },
  {
    id: "pres-polar-1",
    productId: "prod-polar",
    name: "Individual",
    unitsPerPresentation: 1,
    price: { usd: 1, bs: 370 },
    active: true,
  },
  {
    id: "pres-polar-balde",
    productId: "prod-polar",
    name: "Balde",
    unitsPerPresentation: 6,
    price: { usd: 5, bs: 1850 },
    active: true,
  },
  {
    id: "pres-polar-caja",
    productId: "prod-polar",
    name: "Caja",
    unitsPerPresentation: 36,
    price: { usd: 28, bs: 10360 },
    active: true,
  },
  {
    id: "pres-ron-1",
    productId: "prod-ron",
    name: "Botella 750ml",
    unitsPerPresentation: 1,
    price: { usd: 22, bs: 8140 },
    active: true,
  },
  {
    id: "pres-ref-1",
    productId: "prod-refresco",
    name: "Unidad",
    unitsPerPresentation: 1,
    price: { usd: 1.5, bs: 555 },
    active: true,
  },
  {
    id: "pres-agua-1",
    productId: "prod-agua",
    name: "Unidad",
    unitsPerPresentation: 1,
    price: { usd: 0.6, bs: 220 },
    active: true,
  },
];

export const AD_DEMO_INVENTORY: AdInventoryItem[] = [
  /** Bodegón / Licorería — Cerveza Regional alineada a escenario COP. */
  { productId: "prod-regional", warehouseId: "wh-1", qtyBase: 40 },
  { productId: "prod-regional", warehouseId: "wh-2", qtyBase: 70 },
  { productId: "prod-polar", warehouseId: "wh-1", qtyBase: 800 },
  { productId: "prod-polar", warehouseId: "wh-2", qtyBase: 90 },
  { productId: "prod-ron", warehouseId: "wh-1", qtyBase: 40 },
  { productId: "prod-ron", warehouseId: "wh-2", qtyBase: 8 },
  { productId: "prod-refresco", warehouseId: "wh-1", qtyBase: 200 },
  { productId: "prod-refresco", warehouseId: "wh-2", qtyBase: 40 },
  { productId: "prod-agua", warehouseId: "wh-1", qtyBase: 300 },
  { productId: "prod-agua", warehouseId: "wh-2", qtyBase: 50 },
];

export const AD_DEMO_TABLES: AdTable[] = [
  {
    id: "mesa-1",
    number: "1",
    code: "MESA-01",
    spaceType: "mesa",
    capacity: 4,
    status: "disponible",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "mesa-2",
    number: "2",
    code: "MESA-02",
    spaceType: "mesa",
    capacity: 4,
    status: "ocupada",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "mesa-3",
    number: "3",
    code: "MESA-03",
    spaceType: "mesa",
    capacity: 6,
    status: "cuenta_abierta",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "mesa-8",
    number: "8",
    code: "MESA-08",
    spaceType: "mesa",
    capacity: 6,
    status: "disponible",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "mesa-12",
    number: "12",
    code: "MESA-12",
    spaceType: "mesa",
    capacity: 8,
    status: "cuenta_prepagada",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "mesa-18",
    number: "18",
    code: "MESA-18",
    spaceType: "mesa",
    capacity: 4,
    status: "disponible",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "bar-01",
    number: "B1",
    code: "BAR-01",
    label: "Barra principal",
    spaceType: "barra",
    capacity: 10,
    status: "disponible",
    active: true,
    warehouseId: "wh-2",
  },
  {
    id: "terraza-01",
    number: "T1",
    code: "TERRAZA-01",
    spaceType: "terraza",
    capacity: 12,
    status: "disponible",
    active: true,
    warehouseId: "wh-1",
  },
  {
    id: "privado-01",
    number: "P1",
    code: "PRIVADO-01",
    spaceType: "privado",
    capacity: 8,
    status: "disponible",
    active: true,
    warehouseId: "wh-1",
  },
];

export const AD_DEMO_CUSTOMERS: AdCustomer[] = [
  {
    id: "cli-1",
    firstName: "Juan",
    lastName: "Pérez",
    name: "Juan Pérez",
    phone: "0414-0000000",
    documentId: "V-12345678",
    email: "juan@example.com",
    address: "Valencia, Carabobo",
    notes: "Cliente frecuente — prepago cerveza",
    active: true,
    createdAt: now(),
  },
  {
    id: "cli-2",
    firstName: "Eventos",
    lastName: "Corporativos",
    name: "Eventos Corporativos",
    phone: "0424-1111111",
    notes: "Pedidos por caja",
    active: true,
    createdAt: now(),
  },
];

export const AD_DEMO_ACCOUNTS: AdAccount[] = [
  {
    id: "acc-184",
    number: "000184",
    tableId: "mesa-12",
    mesoneraId: "op-ana",
    mesoneraName: "Ana",
    customerId: "cli-1",
    customerName: "Juan Pérez",
    customerPhone: "0414-0000000",
    status: "PREPAGADA",
    prepaid: true,
    items: [
      {
        id: "acci-1",
        productId: "prod-regional",
        presentationId: "pres-reg-1",
        qty: 20,
        qtyServed: 5,
        unitPrice: { usd: 1, bs: 370 },
        qtyBase: 20,
      },
    ],
    payments: [
      {
        id: "pay-1",
        method: "efectivo_usd",
        currency: "USD",
        amount: 20,
        createdAt: now(),
      },
    ],
    discountUsd: 0,
    discountBs: 0,
    openedAt: now(),
    updatedAt: now(),
  },
  {
    id: "acc-185",
    number: "000185",
    tableId: "mesa-3",
    mesoneraId: "op-ana",
    mesoneraName: "Ana",
    status: "ABIERTA",
    prepaid: false,
    items: [
      {
        id: "acci-2",
        productId: "prod-polar",
        presentationId: "pres-polar-1",
        qty: 8,
        qtyServed: 8,
        unitPrice: { usd: 1, bs: 370 },
        qtyBase: 8,
      },
    ],
    payments: [],
    discountUsd: 0,
    discountBs: 0,
    openedAt: now(),
    updatedAt: now(),
  },
];

export const AD_DEMO_PREPAIDS: AdPrepaidAccount[] = [
  {
    id: "pp-125",
    code: "PRE-2026-000125",
    qrToken: "ad_qr_pre_2026_000125_x7k9m2",
    customerId: "cli-1",
    customerName: "Juan Pérez",
    customerPhone: "0414-0000000",
    customerDocumentId: "V-12345678",
    status: "ACTIVO",
    items: [
      {
        id: "ppi-1",
        productId: "prod-regional",
        presentationId: "pres-reg-1",
        qtyPurchased: 20,
        qtyConsumed: 11,
        unitPrice: { usd: 1, bs: 370 },
        qtyBasePerUnit: 1,
      },
      {
        id: "ppi-2",
        productId: "prod-refresco",
        presentationId: "pres-ref-1",
        qtyPurchased: 3,
        qtyConsumed: 1,
        unitPrice: { usd: 1.5, bs: 555 },
        qtyBasePerUnit: 1,
      },
      {
        id: "ppi-3",
        productId: "prod-agua",
        presentationId: "pres-agua-1",
        qtyPurchased: 2,
        qtyConsumed: 2,
        unitPrice: { usd: 0.6, bs: 220 },
        qtyBasePerUnit: 1,
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
];

export const AD_DEMO_PREPAID_CONSUMPTIONS: AdPrepaidConsumption[] = [
  {
    id: "ppc-1",
    prepaidId: "pp-125",
    productId: "prod-regional",
    presentationId: "pres-reg-1",
    qty: 4,
    qtyBase: 4,
    mesoneraName: "Ana",
    createdAt: now(),
  },
  {
    id: "ppc-2",
    prepaidId: "pp-125",
    productId: "prod-regional",
    presentationId: "pres-reg-1",
    qty: 7,
    qtyBase: 7,
    mesoneraName: "Ana",
    createdAt: now(),
  },
  {
    id: "ppc-3",
    prepaidId: "pp-125",
    productId: "prod-refresco",
    presentationId: "pres-ref-1",
    qty: 1,
    qtyBase: 1,
    mesoneraName: "Ana",
    createdAt: now(),
  },
  {
    id: "ppc-4",
    prepaidId: "pp-125",
    productId: "prod-agua",
    presentationId: "pres-agua-1",
    qty: 2,
    qtyBase: 2,
    mesoneraName: "Ana",
    createdAt: now(),
  },
];

export const AD_DEMO_MOVEMENTS: AdInventoryMovement[] = [
  {
    id: "mov-1",
    type: "TRASLADO_SALIDA",
    productId: "prod-regional",
    presentationId: "pres-reg-1",
    qtyPresentation: 100,
    qtyBase: 100,
    warehouseId: "wh-1",
    warehouseFromId: "wh-1",
    warehouseToId: "wh-2",
    userName: "Admin A&D",
    reason: "Reposición Depósito 2",
    createdAt: now(),
  },
  {
    id: "mov-2",
    type: "TRASLADO_ENTRADA",
    productId: "prod-regional",
    presentationId: "pres-reg-1",
    qtyPresentation: 100,
    qtyBase: 100,
    warehouseId: "wh-2",
    warehouseFromId: "wh-1",
    warehouseToId: "wh-2",
    userName: "Admin A&D",
    reason: "Reposición Depósito 2",
    createdAt: now(),
  },
];

export const AD_DEMO_SALES: AdSale[] = [];
export const AD_DEMO_RECEIPTS: AdReceipt[] = [];
export const AD_DEMO_PURCHASES: AdPurchase[] = [];
export const AD_DEMO_WHATSAPP_LOGS: AdWhatsAppLog[] = [];
export const AD_DEMO_SERVICE_LOGS: AdServiceLog[] = [];
export const AD_DEMO_DAILY_CLOSURES: AdDailyClosure[] = [];
export const AD_DEMO_INVENTORY_CLOSURES: AdInventoryClosure[] = [];

export const AD_DEMO_AUDIT: AdAuditEvent[] = [
  {
    id: "aud-1",
    action: "traslado",
    entity: "inventario",
    entityId: "mov-1",
    userName: "Admin A&D",
    detail: "100 Regional: DEP1 → DEP2",
    beforeValue: "DEP1=1000 DEP2=120",
    afterValue: "DEP1=900 DEP2=220",
    reason: "Reposición",
    createdAt: now(),
  },
];
