export const ROLES = ["admin", "editor", "manager", "viewer"] as const;
export type Role = (typeof ROLES)[number];

export const PERMISSIONS = [
  "dashboard:view",
  "users:view",
  "users:manage",
  "roles:view",
  "roles:manage",
  "blog:view",
  "blog:manage",
  "academy:view",
  "academy:manage",
  "media:view",
  "media:manage",
  "products:view",
  "products:manage",
  "services:view",
  "services:manage",
  "cases:view",
  "cases:manage",
  "files:view",
  "files:manage",
  "settings:view",
  "settings:manage",
  "profile:view",
  "profile:manage",
] as const;
export type Permission = (typeof PERMISSIONS)[number];

export const rolePermissions: Record<Role, readonly Permission[]> = {
  admin: PERMISSIONS,
  editor: [
    "dashboard:view",
    "blog:view",
    "blog:manage",
    "academy:view",
    "academy:manage",
    "media:view",
    "media:manage",
    "cases:view",
    "files:view",
    "profile:view",
    "profile:manage",
  ],
  manager: [
    "dashboard:view",
    "users:view",
    "blog:view",
    "academy:view",
    "media:view",
    "products:view",
    "services:view",
    "cases:view",
    "files:view",
    "settings:view",
    "profile:view",
    "profile:manage",
  ],
  viewer: [
    "dashboard:view",
    "blog:view",
    "academy:view",
    "media:view",
    "products:view",
    "services:view",
    "cases:view",
    "files:view",
    "profile:view",
  ],
};
