import type {
  AdTvContent,
  AdTvGroup,
  AdTvScreen,
} from "@/types/ad-tv";

const now = () => new Date().toISOString();

export const AD_DEMO_TV_CONTENTS: AdTvContent[] = [
  {
    id: "tvc-promo-viernes",
    name: "Promoción viernes",
    type: "PROMOTION",
    url: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=1280",
    durationSec: 14,
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvc-promo-cerveza",
    name: "Promoción Cerveza",
    type: "PROMOTION",
    url: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=1280",
    durationSec: 12,
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvc-video-bienvenida",
    name: "Video Institucional",
    type: "VIDEO",
    url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    durationSec: 30,
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvc-promo-finde",
    name: "Promoción Fin de Semana",
    type: "PROMOTION",
    url: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1280",
    durationSec: 15,
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvc-menu",
    name: "Menú de la Casa",
    type: "MENU",
    url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1280",
    durationSec: 20,
    active: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvc-texto",
    name: "Bienvenida texto",
    type: "TEXT",
    url: "",
    durationSec: 8,
    active: true,
    notes: "Bienvenidos a A&D Licorería & Bodegón",
    createdAt: now(),
    updatedAt: now(),
  },
];

export const AD_DEMO_TV_SCREENS: AdTvScreen[] = [
  {
    id: "tvs-001",
    code: "TV-001",
    name: "TV Barra",
    location: "Barra",
    status: "OFFLINE",
    pairingCode: null,
    pairingToken: null,
    paired: false,
    currentContentId: null,
    currentGroupId: "tvg-barra",
    volume: 70,
    isMuted: false,
    playbackState: "IDLE",
    positionSec: 0,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvs-002",
    code: "TV-002",
    name: "TV Salón",
    location: "Salón",
    status: "OFFLINE",
    pairingCode: null,
    pairingToken: null,
    paired: false,
    currentContentId: "tvc-video-bienvenida",
    currentGroupId: "tvg-salon",
    volume: 60,
    isMuted: false,
    playbackState: "IDLE",
    positionSec: 0,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvs-003",
    code: "TV-003",
    name: "TV Terraza",
    location: "Terraza",
    status: "OFFLINE",
    pairingCode: null,
    pairingToken: null,
    paired: false,
    currentContentId: null,
    currentGroupId: "tvg-terraza",
    volume: 50,
    isMuted: false,
    playbackState: "IDLE",
    positionSec: 0,
    createdAt: now(),
    updatedAt: now(),
  },
];

export const AD_DEMO_TV_GROUPS: AdTvGroup[] = [
  {
    id: "tvg-todos",
    name: "TODOS",
    code: "TODOS",
    screenIds: ["tvs-001", "tvs-002", "tvs-003"],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvg-licoreria",
    name: "LICORERÍA",
    code: "LICORERIA",
    screenIds: ["tvs-001", "tvs-002"],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvg-bodegon",
    name: "BODEGÓN",
    code: "BODEGON",
    screenIds: [],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvg-barra",
    name: "BARRA",
    code: "BARRA",
    screenIds: ["tvs-001"],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvg-salon",
    name: "SALÓN",
    code: "SALON",
    screenIds: ["tvs-002"],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tvg-terraza",
    name: "TERRAZA",
    code: "TERRAZA",
    screenIds: ["tvs-003"],
    createdAt: now(),
    updatedAt: now(),
  },
];
